#!/usr/bin/env python3
"""
build_start_v30.py — Génère start.bat v3.0 (CRLF garanti)

Architecture v3.0 :
  PHASE 1 — Vérification fichiers (backend.exe, runtime.exe, VSCodium.exe, extension.js)
  PHASE 2 — Lancer runtime.exe  (port 6000, timeout 300s, message toutes les 15s)
  PHASE 3 — Lancer backend.exe  (port 5000, timeout 60s, erreur fatale si absent)
  PHASE 4 — Lancer VSCodium     (--extensions-dir, --user-data-dir, --extensionDevelopmentPath)
  FIN      — keep_alive loop (timeout /t 30)

Supprimé : Node.js, winget, MSI, PowerShell install, HKCU\Run, reboot,
           refresh_node_path, npm install, server.js check — 293 lignes
"""

OUTPUT = "/home/user/webapp/start.bat"

LINES = [
    r"@echo off",
    r"setlocal enabledelayedexpansion",
    r"title Sudo Studio - Starting",
    r"",
    r":: ============================================================",
    r"::   SUDO STUDIO v3.0 -- Windows Launcher",
    r"::   backend.exe and runtime.exe include Node.js/Python.",
    r"::   No system dependencies required.",
    r":: ============================================================",
    r"",
    r":: -- Global variables ----------------------------------------",
    r'set "ROOT=%~dp0"',
    r'set "APP=%ROOT%app"',
    r'set "LOGS=%ROOT%logs"',
    r'set "LOG_FILE=%ROOT%logs\startup.log"',
    r'set "BACKEND_PORT=5000"',
    r'set "RUNTIME_PORT=6000"',
    r'set "EXT=%APP%\extensions\sudo-ai"',
    r'set "DATA=%APP%\data"',
    r'set "START_TIME=%TIME%"',
    r'set "START_DATE=%DATE%"',
    r"",
    r":: -- Create logs folder if missing ---------------------------",
    r'if not exist "%LOGS%" mkdir "%LOGS%" 2>nul',
    r'if not exist "%LOGS%" (',
    r"    echo [ERROR] Cannot create logs folder.",
    r"    echo         Check permissions: %ROOT%",
    r"    pause",
    r"    exit /b 1",
    r")",
    r"",
    r":: -- Init log file -------------------------------------------",
    r"(",
    r"echo ============================================================",
    r"echo   SUDO STUDIO v3.0 - Started: %START_DATE% %START_TIME%",
    r"echo   Root: %ROOT%",
    r"echo   App : %APP%",
    r"echo ============================================================",
    r') > "%LOG_FILE%"',
    r"",
    r"echo.",
    r"echo ============================================================",
    r"echo   SUDO STUDIO v3.0 - Starting...",
    r"echo ============================================================",
    r"echo.",
    r"",
    r":: ============================================================",
    r"::  SUBROUTINES (must be defined before GOTO targets call them)",
    r":: ============================================================",
    r"goto :main",
    r"",
    r":: -- Subroutine: write to log --------------------------------",
    r":LOG",
    r'    echo %~1 >> "%LOG_FILE%" 2>nul',
    r"    exit /b 0",
    r"",
    r":: -- Subroutine: HTTP health check --------------------------",
    r":: Usage: call :check_port <port> <path> <result_var>",
    r":: Sets result_var=1 if HTTP 200, else 0",
    r":check_port",
    r'    set "%~3=0"',
    r"    curl --version >nul 2>&1",
    r"    if !errorlevel! equ 0 (",
    r'        curl -s -o nul -w "%%{http_code}" http://localhost:%~1%~2 2>nul | findstr /B "200" >nul 2>&1',
    r'        if !errorlevel! equ 0 set "%~3=1"',
    r"    ) else (",
    r"        powershell -NoProfile -Command \"try{$r=(Invoke-WebRequest -Uri 'http://localhost:%~1%~2' -TimeoutSec 2 -UseBasicParsing -ErrorAction Stop);if($r.StatusCode -eq 200){exit 0}else{exit 1}}catch{exit 1}\" >nul 2>&1",
    r'        if !errorlevel! equ 0 set "%~3=1"',
    r"    )",
    r"    exit /b 0",
    r"",
    r":: ============================================================",
    r":main",
    r":: ============================================================",
    r"::  PHASE 1 -- FILE VERIFICATION (< 5 seconds)",
    r":: ============================================================",
    r'call :LOG "[PHASE 1] Verifying required files..."',
    r"echo [1/4] Verifying application files...",
    r"",
    r":: Check backend.exe",
    r'if not exist "%APP%\backend.exe" (',
    r'    call :LOG "[PHASE 1] ERROR: backend.exe not found"',
    r"    echo.",
    r"    echo   [ERROR] backend.exe not found",
    r"    echo           Expected: %APP%\backend.exe",
    r"    echo           Please reinstall SudoStudio.",
    r"    echo.",
    r"    pause",
    r"    exit /b 1",
    r")",
    r"",
    r":: Check runtime.exe",
    r'if not exist "%APP%\runtime.exe" (',
    r'    call :LOG "[PHASE 1] ERROR: runtime.exe not found"',
    r"    echo.",
    r"    echo   [ERROR] runtime.exe not found",
    r"    echo           Expected: %APP%\runtime.exe",
    r"    echo           Please reinstall SudoStudio.",
    r"    echo.",
    r"    pause",
    r"    exit /b 1",
    r")",
    r"",
    r":: Check VSCodium.exe",
    r'if not exist "%APP%\VSCodium.exe" (',
    r'    call :LOG "[PHASE 1] ERROR: VSCodium.exe not found"',
    r"    echo.",
    r"    echo   [ERROR] VSCodium.exe not found",
    r"    echo           Expected: %APP%\VSCodium.exe",
    r"    echo           Please reinstall SudoStudio.",
    r"    echo.",
    r"    pause",
    r"    exit /b 1",
    r")",
    r"",
    r":: Check Sudo AI extension (warning only — not fatal)",
    r'if not exist "%EXT%\extension.js" (',
    r'    call :LOG "[PHASE 1] WARNING: Sudo AI extension not found at %EXT%"',
    r"    echo.",
    r"    echo   [WARNING] Sudo AI extension not found.",
    r"    echo             VSCodium will open without Sudo AI features.",
    r"    echo.",
    r")",
    r"",
    r'call :LOG "[PHASE 1] All required files verified OK"',
    r"echo [1/4] Files OK",
    r"",
    r":: ============================================================",
    r"::  PHASE 2 -- AI RUNTIME (port 6000)",
    r"::  runtime.exe embeds Python + AI model loader",
    r"::  First run downloads AI model (~600 MB) -- up to 5 minutes",
    r":: ============================================================",
    r"echo.",
    r"echo [2/4] Starting AI Runtime (port %RUNTIME_PORT%)...",
    r"echo        First run downloads AI model (~600MB, may take minutes)",
    r'call :LOG "[PHASE 2] Launching runtime.exe on port %RUNTIME_PORT%"',
    r"",
    r'start "SudoRuntime" /B cmd /c ^""%APP%\runtime.exe" >> "%LOGS%\runtime.log" 2^>&1^"',
    r'call :LOG "[PHASE 2] runtime.exe launched"',
    r"",
    r":: -- Poll port 6000 -- timeout 300s (first run downloads model) --",
    r'set "RUNTIME_READY=0"',
    r'set "WAIT_COUNT=0"',
    r'set "LAST_MSG=0"',
    r":wait_runtime",
    r"    set /a WAIT_COUNT+=1",
    r"    if !WAIT_COUNT! gtr 150 goto :runtime_done",
    r"    timeout /t 2 /nobreak >nul",
    r"    call :check_port %RUNTIME_PORT% /health RUNTIME_HIT",
    r'    if "!RUNTIME_HIT!"=="1" (',
    r'        set "RUNTIME_READY=1"',
    r"        goto :runtime_done",
    r"    )",
    r"    :: Print status every 15 seconds (every 7-8 polls of 2s)",
    r"    set /a ELAPSED=WAIT_COUNT*2",
    r"    set /a MSG_SLOT=ELAPSED/15",
    r"    if !MSG_SLOT! gtr !LAST_MSG! (",
    r'        set "LAST_MSG=!MSG_SLOT!"',
    r"        echo        Still loading AI model... (!ELAPSED!s elapsed)",
    r"    )",
    r"    goto :wait_runtime",
    r":runtime_done",
    r"",
    r'if "!RUNTIME_READY!"=="1" (',
    r'    call :LOG "[PHASE 2] AI Runtime ready on port %RUNTIME_PORT%"',
    r"    echo [2/4] AI Runtime ready on port %RUNTIME_PORT%",
    r") else (",
    r'    call :LOG "[PHASE 2] WARNING: Runtime not responding after 300s -- continuing"',
    r"    echo.",
    r"    echo   [WARNING] AI Runtime not responding after 5 minutes.",
    r"    echo             AI features may be limited. Continuing anyway...",
    r"    echo             Check: %LOGS%\runtime.log",
    r"    echo.",
    r")",
    r"",
    r":: ============================================================",
    r"::  PHASE 3 -- BACKEND (port 5000)",
    r"::  backend.exe embeds Node.js (compiled with pkg node18-win-x64)",
    r"::  NO system Node.js required",
    r":: ============================================================",
    r"echo.",
    r"echo [3/4] Starting Backend (port %BACKEND_PORT%)...",
    r'call :LOG "[PHASE 3] Launching backend.exe on port %BACKEND_PORT%"',
    r"",
    r'start "SudoBackend" /B cmd /c ^""%APP%\backend.exe" >> "%LOGS%\backend.log" 2^>&1^"',
    r'call :LOG "[PHASE 3] backend.exe launched"',
    r"",
    r":: -- Poll port 5000 -- timeout 60 seconds -------------------",
    r'set "BACKEND_READY=0"',
    r'set "WAIT_COUNT=0"',
    r":wait_backend",
    r"    set /a WAIT_COUNT+=1",
    r"    if !WAIT_COUNT! gtr 60 goto :backend_done",
    r"    timeout /t 1 /nobreak >nul",
    r"    call :check_port %BACKEND_PORT% /api/system/health BACKEND_HIT",
    r'    if "!BACKEND_HIT!"=="1" (',
    r'        set "BACKEND_READY=1"',
    r"        goto :backend_done",
    r"    )",
    r"    goto :wait_backend",
    r":backend_done",
    r"",
    r'if "!BACKEND_READY!"=="1" (',
    r'    call :LOG "[PHASE 3] Backend ready on port %BACKEND_PORT%"',
    r"    echo [3/4] Backend ready on port %BACKEND_PORT%",
    r") else (",
    r'    call :LOG "[PHASE 3] ERROR: Backend not responding after 60s"',
    r"    echo.",
    r"    echo   [ERROR] Backend not responding after 60 seconds.",
    r"    echo.",
    r"    echo   Check log: %LOGS%\backend.log",
    r"    if exist ""%LOGS%\backend.log"" (",
    r"        echo   Last lines:",
    r"        powershell -NoProfile -Command \"Get-Content '%LOGS%\backend.log' -Tail 8 -ErrorAction SilentlyContinue\" 2>nul",
    r"        echo.",
    r"    )",
    r"    echo   Solutions:",
    r"    echo     1. Check that port %BACKEND_PORT% is not already in use",
    r"    echo     2. Relaunch start.bat",
    r"    echo.",
    r"    pause",
    r"    exit /b 1",
    r")",
    r"",
    r":: ============================================================",
    r"::  PHASE 4 -- VSCODIUM + SUDO AI EXTENSION",
    r":: ============================================================",
    r"echo.",
    r"echo [4/4] Opening Sudo Studio in VSCodium...",
    r'call :LOG "[PHASE 4] Launching VSCodium"',
    r"",
    r":: Create data dirs if missing",
    r'if not exist "%DATA%" mkdir "%DATA%" 2>nul',
    r'if not exist "%APP%\extensions" mkdir "%APP%\extensions" 2>nul',
    r"",
    r'set "VSCO_EXE=%APP%\VSCodium.exe"',
    r'set "VSCO_EXT_DIR=%APP%\extensions"',
    r'set "VSCO_USER_DIR=%DATA%"',
    r'set "VSCO_EXT_SRC=%EXT%"',
    r'call :LOG "[PHASE 4] EXE     : !VSCO_EXE!"',
    r'call :LOG "[PHASE 4] Ext-dir : !VSCO_EXT_DIR!"',
    r'call :LOG "[PHASE 4] Data-dir: !VSCO_USER_DIR!"',
    r'call :LOG "[PHASE 4] Ext-src : !VSCO_EXT_SRC!"',
    r"",
    r'start "SudoStudio" "!VSCO_EXE!" --extensions-dir "!VSCO_EXT_DIR!" --user-data-dir "!VSCO_USER_DIR!" --extensionDevelopmentPath "!VSCO_EXT_SRC!"',
    r"",
    r"echo [4/4] VSCodium launched with Sudo AI",
    r'call :LOG "[PHASE 4] VSCodium launched OK"',
    r"",
    r":: ============================================================",
    r"::  ALL SERVICES RUNNING",
    r":: ============================================================",
    r'call :LOG "[OK] Sudo Studio v3.0 started successfully - %TIME%"',
    r"echo.",
    r"echo ============================================================",
    r"echo   SUDO STUDIO IS RUNNING",
    r"echo ============================================================",
    r"echo.",
    r"echo   Backend   : http://localhost:%BACKEND_PORT%",
    r"echo   AI Runtime: http://localhost:%RUNTIME_PORT%",
    r"echo.",
    r"echo   Logs      : %LOGS%\startup.log",
    r"echo   Backend   : %LOGS%\backend.log",
    r"echo   Runtime   : %LOGS%\runtime.log",
    r"echo.",
    r"echo ============================================================",
    r"echo.",
    r"echo   Keep this window open to maintain services.",
    r"echo   Close this window to stop everything.",
    r"echo.",
    r'echo %date% %time% - ALL SERVICES STARTED >> "%LOG_FILE%"',
    r"",
    r":: -- Keep terminal open (services stay alive as children) ----",
    r":keep_alive",
    r"timeout /t 30 /nobreak >nul",
    r"goto :keep_alive",
]

# Write with guaranteed CRLF
content = "\r\n".join(LINES) + "\r\n"
with open(OUTPUT, "wb") as f:
    f.write(content.encode("utf-8"))

total = len(LINES)
print(f"OK: start.bat v3.0 written — {total} lines (CRLF)")
print(f"    Output: {OUTPUT}")
